### PR TITLE
using MyPlugins instead of Plugins to bypass Chrome's blacklist

### PR DESCRIPTION
**Pull request by skehlet**
Just working around Chrome's aggressive blacklisting of "Application Support/SIMBL/Plugins" until they get that all resolved. Testing and  working with Chrome 14.0.825.163.

### CODE REVIEW

**Comment by albertz** [comment]
Have you really tried this? I wonder that it works because from the Chrome source, it looks that it blocks everything from `/Library` and `~`. Also, it is no really good solution to change the directory name completely. It should always be backwards compatible, i.e. search also in the old directory.

The patch I have introduced earlier already works around the Chrome blacklist. You can just put your plugins into `/System/Library/...`.

So this is not really needed.

**Comment by skehlet** [comment]
Yes, it works, using it right now, Chrome 14.0.835.186 and Afloat. Yes, it requires both your changes to look in /System/Library instead of /Library and mine to rename the suffix from "Application Support/SIMBL/Plugins" to "Application Support/SIMBL/MyPlugins". Your change alone no longer works because of the [blocked_suffixes here](http://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/mac/cfbundle_blocker.mm?r1=97497&r2=97496&pathrev=97497). I agree the change Plugins -> MyPlugins is not desirable long-term but my goal was simply to get Afloat to work, when the Chrome guys get this all straightened out I'd want to go back to the official SIMBL distro anyway. Thanks for your effort in digging into this. No need to pull in my changes, if for whatever reason, it's still working for you.

**Comment by albertz** [comment]
No, both changes are not required. Only one is. From the code you have linked, the list of blocked path is build by all combinations of blocked suffixes and blocked prefixes. Because `/System/` is not in the list of blocked suffixes, nothing in `/System` will be blocked.

Just create the directory `/System/Library/Application Support/SIMBL/Plugins` and put the plugins in there.

**Comment by skehlet** [comment]
You are correct. It didn't work for me initially, but it must have been my failure to build and/or install it correctly. Which is still weird, because every app worked but Chrome (hmm, maybe I didn't build the 32 bit version properly, would make sense). So my change to `MyPlugins` wasn't necessary, it just happened to work when I tried it that time. I've switched back and it's working fine now. Thanks for your assistance resolving this.

**Comment by albertz** [comment]
No problem. Good to know your feedback on this. :)

**Pull request closed without merging**
